<?php
/*
Plugin Name: WP Share Dynamic Cards
Plugin URI: https://github.com/sethrubenstein/wp-share-dynamic-cards
Description: Lets you share a post while changing the image, title, description for a shared card (Twitter or Facebook)
Version: 1.0
Author: Seth Rubenstein
Author URI: http://sethrubenstein.info
*/

// {site_url}/share/{post_id}/{image_id}

function wpsdc_rewrite_activation(){
    flush_rewrite_rules();
}
register_activation_hook( __FILE__, 'wpsdc_rewrite_activation' );

function wpsdc_rewrite_add_var( $vars ){
    $vars[] = 'postid';
    $vars[] = 'imageid';    
    return $vars;
}
add_filter( 'query_vars', 'wpsdc_rewrite_add_var' );

function wpsdc_rewrite_rule() {
    add_rewrite_rule('^share/([^/]*)/([^/]*)/?','index.php?postid=$matches[1]&imageid=$matches[2]','top');
}
add_action('init', 'wpsdc_rewrite_rule', 10, 0);

function wpsdc_get_share_url($postID, $imageID) {
    return get_bloginfo( 'url' ).'/share/'.$postID.'/'.$imageID;
}

function wpsdc_rewrite_catch() {
    if( get_query_var( 'imageid' ) && get_query_var( 'postid' ) ) {
        $site_name = apply_filters( 'wpsdc_site_name', get_bloginfo( 'name' ) );
        $twitter_username = apply_filters( 'wpsdc_twitter_username', 'sethrubenstein' );
        $twitter_creator = apply_filters( 'wpsdc_twitter_creator', 'sethrubenstein' );

        $postID = get_query_var( 'postid' );
        $post_OBJ = get_post( $postID );
        $image_size = apply_filters( 'wpsdc_image_size', 'large' );
        $image_OBJ = wp_get_attachment_image_src( get_query_var( 'imageid' ), $image_size );
        $title = $post_OBJ->post_title;
        $description = $post_OBJ->post_excerpt;
        ?>
        <html lang="en-US">
        <head>
        <meta charset="UTF-8">
        <!-- Misc -->
        <meta property="og:locale" content="en_US" />
        <meta property="og:site_name" content="<?php echo $site_name;?>" />
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="@<?php echo $twitter_username;?>">
        <meta property="og:type" content="article" />
        <!-- Facebook -->
        <meta property="og:image" content="<?php echo $image_OBJ[0];?>" />
        <meta property="og:image:width" content="<?php echo $image_OBJ[1];?>" />
        <meta property="og:image:height" content="<?php echo $image_OBJ[2];?>" />
        <meta property="og:title" content="<?php echo $title;?>" />
        <meta property="og:description" content="<?php echo $description;?>" />
        <meta property="og:url" content="<?php echo get_permalink($postID);?>" />
        <meta property="article:published_time" content="<?php echo get_the_date( 'Y-m-d', $postID );?>" />
        <!-- Twitter -->
        <meta name="twitter:creator" content="@<?php echo $twitter_creator;?>">
        <meta name="twitter:title" content="<?php echo $title;?>">
        <meta name="twitter:description" content="<?php echo $description;?>">
        <meta name="twitter:image" content="<?php echo $image_OBJ[0];?>">
        </head>
        <body>
        <!-- This is generated by Seth Rubenstein's WP Share Dynamic Cards plugin. https://github.com/sethrubenstein/wp-share-dynamic-cards -->
        </body>
        </html>
        <?php
        exit();
    }
}
add_action( 'template_redirect', 'wpsdc_rewrite_catch' );